// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1-cMfg4cwcp3JcQPKosGTTzwx2nQFg7I',
    appId: '1:477085028937:web:6f3d2f7ce80723e21c2598',
    messagingSenderId: '477085028937',
    projectId: 'medgenie-c0c97',
    authDomain: 'medgenie-c0c97.firebaseapp.com',
    storageBucket: 'medgenie-c0c97.appspot.com',
    measurementId: 'G-2Q2KGV6YXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLGZH2bBsHi5MX0PQaEY7mHR-TT980NQ',
    appId: '1:477085028937:android:58052656ec2936dc1c2598',
    messagingSenderId: '477085028937',
    projectId: 'medgenie-c0c97',
    storageBucket: 'medgenie-c0c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxQXvZcNhOqKXksehzWZxmA7qHn0qCfI',
    appId: '1:477085028937:ios:69e69a2ba581370f1c2598',
    messagingSenderId: '477085028937',
    projectId: 'medgenie-c0c97',
    storageBucket: 'medgenie-c0c97.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfxQXvZcNhOqKXksehzWZxmA7qHn0qCfI',
    appId: '1:477085028937:ios:69e69a2ba581370f1c2598',
    messagingSenderId: '477085028937',
    projectId: 'medgenie-c0c97',
    storageBucket: 'medgenie-c0c97.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1-cMfg4cwcp3JcQPKosGTTzwx2nQFg7I',
    appId: '1:477085028937:web:b19f5e459d1819051c2598',
    messagingSenderId: '477085028937',
    projectId: 'medgenie-c0c97',
    authDomain: 'medgenie-c0c97.firebaseapp.com',
    storageBucket: 'medgenie-c0c97.appspot.com',
    measurementId: 'G-KYCYE0T7JL',
  );

}